apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Module name
    value: nr-results-exam
  - name: COMPONENT
    description: Component name
    value: backend
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: HOSTNAME
    description: Frontend hostname (without protocol), e.g. nr-results-exam-12-frontend.apps.silver.devops.gov.bc.ca
    required: true
  - name: TAG
    description: Image tag; e.g. PR number, latest or prod
    required: true
  - name: CPU_REQUEST
    value: "25m"
  - name: MEMORY_REQUEST
    value: "50Mi"
  - name: CPU_LIMIT
    value: "75m"
  - name: MEMORY_LIMIT
    value: "150Mi"
  - name: MIN_REPLICAS
    description: The minimum amount of replicas for the horizontal pod autoscaler.
    value: "3"
  - name: MAX_REPLICAS
    description: The maximum amount of replicas for the horizontal pod autoscaler.
    value: "5"
  - name: REGISTRY
    description: Container registry to import from (internal is image-registry.openshift-image-registry.svc:5000)
    value: ghcr.io
  - name: ORG
    description: Organization name, e.g. bcgov
    value: bcgov
  - name: CHES_TOKEN_URL
    value: "https://test.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token"
  - name: CHES_CLIENT_ID
    value: "09C5071A-ACE9B6FACF6"
  - name: S3_ACCESSKEY
    description: Access key for S3
    value: nr-fsa-tst
  - name: S3_ENDPOINT
    description: Endpoint for S3
    value: nrs.objectstore.gov.bc.ca
  - name: S3_BUCKETNAME
    description: Bucket name for S3
    value: tivpth
  - name: VITE_USER_POOLS_ID
    description: AWS Cognito User Pool ID
    value: "ca-central-1_UpeAqsYt4"
  - name: VITE_COGNITO_REGION
    description: AWS Cognito region for user pool
    value: ca-central-1
  - name: RANDOM_EXPRESSION
    description: Random expression to make sure deployments update
    from: "[a-zA-Z0-9]{32}"
    generate: expression
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: "${NAME}-${ZONE}"
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      replicas: 1
      selector:
        matchLabels:
          deployment: "${NAME}-${ZONE}-${COMPONENT}"
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: "${NAME}-${ZONE}"
            deployment: "${NAME}-${ZONE}-${COMPONENT}"
        spec:
          containers:
            - image: ${REGISTRY}/${ORG}/${NAME}/${COMPONENT}:${TAG}
              imagePullPolicy: Always
              name: "${NAME}"
              env:
                - name: CHES_CLIENT_ID
                  value: ${CHES_CLIENT_ID}
                - name: CHES_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: ches-client-secret
                - name: CHES_TOKEN_URL
                  value: ${CHES_TOKEN_URL}
                - name: S3_ACCESSKEY
                  value: ${S3_ACCESSKEY}
                - name: S3_BUCKETNAME
                  value: ${S3_BUCKETNAME}
                - name: S3_ENDPOINT
                  value: ${S3_ENDPOINT}
                - name: S3_SECRETKEY
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: s3-secretkey
                - name: FRONTEND_URL
                  value: https://${HOSTNAME}
                - name: RANDOM_EXPRESSION
                  value: ${RANDOM_EXPRESSION}
                - name: VITE_USER_POOLS_ID
                  value: ${VITE_USER_POOLS_ID}
                - name: VITE_COGNITO_REGION
                  value: ${VITE_COGNITO_REGION}
              ports:
                - containerPort: 5000
                  protocol: TCP
              resources:
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
              readinessProbe:
                httpGet:
                  path: /health?deep=true
                  port: 5000
                  scheme: HTTP
                initialDelaySeconds: 25
                periodSeconds: 20
                timeoutSeconds: 5
                successThreshold: 1
                failureThreshold: 4
              livenessProbe:
                successThreshold: 1
                failureThreshold: 3
                httpGet:
                  path: /health
                  port: 5000
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 30
                timeoutSeconds: 5
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: "${NAME}-${ZONE}"
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      ports:
        - name: 5000-tcp
          protocol: TCP
          port: 80
          targetPort: 5000
      selector:
        deployment: "${NAME}-${ZONE}-${COMPONENT}"
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      scaleTargetRef:
        apiVersion: apps.openshift.io/v1
        kind: Deployment
        name: "${NAME}-${ZONE}-${COMPONENT}"
      minReplicas: "${{MIN_REPLICAS}}"
      maxReplicas: "${{MAX_REPLICAS}}"
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 100
