apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /usr/local/bin/readiness-check.sh
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health/live
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
