# OpenShift Route Redirect Template
# This route redirects the old URL pattern to the new URL pattern.
# Deploy this route when the new URL structure is active.
# Note: Verify backend FRONTEND_URL env var is updated to use the new URL when deploying new routes.
#
# Usage examples:
#   TEST: -p ZONE=test -p OLD_HOST=nr-results-exam-test-frontend -p NEW_HOST=results-exam-test
#   PROD: -p ZONE=prod -p OLD_HOST=nr-results-exam-prod-frontend -p NEW_HOST=results-exam
apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Module name
    value: nr-results-exam
  - name: ZONE
    description: Deployment zone, e.g. pr-###, test or prod
    required: true
  - name: OLD_HOST
    description: Old hostname (without domain)
    required: true
  - name: NEW_HOST
    description: New hostname (without domain)
    required: true
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
objects:
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${NAME}-${ZONE}-frontend-redirect
      labels:
        app: ${NAME}-${ZONE}
        purpose: url-redirect
    spec:
      host: ${OLD_HOST}.${DOMAIN}
      redirect:
        to: https://${NEW_HOST}.${DOMAIN}/
        statusCode: 301
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
